[[redirects]]
  from = "/mentoria"
  to = "/servicios"
  status = 301

[[redirects]]
  from = "/guias-y-acompanamientos"
  to = "/servicios"
  status = 301

[[redirects]]
  from = "/formacion"
  to = "/servicios"
  status = 301

[[redirects]]
  from = "/formaciones"
  to = "/servicios"
  status = 301

[[redirects]]
  from = "/formacion/*"
  to = "/servicios"
  status = 301

[[redirects]]
  from = "/arteterapia"
  to = "/servicios"
  status = 301

[[redirects]]
  from = "/about"
  to = "/bio"
  status = 301

[[redirects]]
  from = "/mi-libro"
  to = "/bio"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/"
  status = 301

[[redirects]]
  from = "/contacto"
  to = "/"
  status = 301